#!/bin/bash


if [ "$(expr substr $(uname -s) 1 5)" == "Linux" ]; then
	sudo rm -r /usr/include/ostd 2> /dev/null
	sudo rm -r /usr/include/ogfx 2> /dev/null
	sudo rm -r /usr/lib/libostd.so 2> /dev/null
	sudo rm -r /usr/lib/libogfx.so 2> /dev/null
	sudo cp -r ./Release/include/ostd /usr/include/
	sudo cp -r ./Release/include/ogfx /usr/include/
	sudo cp -r ./Release/lib/libostd.so /usr/lib/
	sudo cp -r ./Release/lib/libogfx.so /usr/lib/
elif [ "$(expr substr $(uname -s) 1 10)" == "MINGW64_NT" ]; then
	# msys_dir=""
	# if [ -z "$1" ]
	# then
	# 	echo "No argument supplied"
	# fi
	rm -r C:/msys64/ucrt64/include/ostd 2> /dev/null
	rm -r C:/msys64/ucrt64/include/ogfx 2> /dev/null
	rm -r C:/msys64/ucrt64/bin/libostd.dll 2> /dev/null
	rm -r C:/msys64/ucrt64/lib/libostd.dll.a 2> /dev/null
	rm -r C:/msys64/ucrt64/bin/libogfx.dll 2> /dev/null
	rm -r C:/msys64/ucrt64/lib/libogfx.dll.a 2> /dev/null
	cp -r ./Release/include/ostd C:/msys64/ucrt64/include/
	cp -r ./Release/include/ogfx C:/msys64/ucrt64/include/
	cp -r ./Release/lib/libostd.dll C:/msys64/ucrt64/bin/
	cp -r ./Release/lib/libostd.dll.a C:/msys64/ucrt64/lib/
	cp -r ./Release/lib/libogfx.dll C:/msys64/ucrt64/bin/
	cp -r ./Release/lib/libogfx.dll.a C:/msys64/ucrt64/lib/
fi
