#include "WaylandAppMenuBinder.hpp"
#include <wayland-client.h>
#include "appmenu-client-protocol.h" // generated by wayland-scanner at build time - see CMakeLists.txt
#include <cstring>

namespace ogfx
{
	namespace gui
	{
		namespace
		{
			struct Impl
			{
				org_kde_kwin_appmenu_manager* manager { nullptr };
				org_kde_kwin_appmenu* appmenu { nullptr };
			};

			void registry_global(void* data, wl_registry* registry, u32 name, const char* interface, u32 version)
			{
				auto* impl = static_cast<Impl*>(data);
				if (std::strcmp(interface, "org_kde_kwin_appmenu_manager") == 0)
					impl->manager = static_cast<org_kde_kwin_appmenu_manager*>(wl_registry_bind(registry, name, &org_kde_kwin_appmenu_manager_interface, 1));
			}

			void registry_global_remove(void* data, wl_registry* registry, u32 name) {  }

			constexpr wl_registry_listener kRegistryListener = { registry_global, registry_global_remove };
		}

		WaylandAppMenuBinder::~WaylandAppMenuBinder(void)
		{
			release();
		}

		bool WaylandAppMenuBinder::bind(void* wlDisplayVoid, void* wlSurfaceVoid)
		{
			auto* display = static_cast<wl_display*>(wlDisplayVoid);
			auto* surface = static_cast<wl_surface*>(wlSurfaceVoid);
			if (!display || !surface)
				return false;

			auto* impl = new Impl();
			wl_registry* registry = wl_display_get_registry(display);
			wl_registry_add_listener(registry, &kRegistryListener, impl);
			// Forces the compositor's one-time burst of wl_registry::global events (emitted in
			// response to get_registry() above) to be read and dispatched now, synchronously -
			// necessary since registry_global only fires in response to those, and we need
			// impl->manager populated before we can use it, below.
			wl_display_roundtrip(display);
			wl_registry_destroy(registry);

			if (!impl->manager)
			{
				delete impl;
				return false; // compositor doesn't advertise this protocol at all
			}
			impl->appmenu = org_kde_kwin_appmenu_manager_create(impl->manager, surface);
			m_impl = impl;
			return impl->appmenu != nullptr;
		}

		void WaylandAppMenuBinder::setAddress(const String& serviceName, const String& objectPath)
		{
			auto* impl = static_cast<Impl*>(m_impl);
			if (impl && impl->appmenu)
				org_kde_kwin_appmenu_set_address(impl->appmenu, serviceName.c_str(), objectPath.c_str());
		}

		void WaylandAppMenuBinder::release(void)
		{
			auto* impl = static_cast<Impl*>(m_impl);
			if (!impl)
				return;
			if (impl->appmenu)
				org_kde_kwin_appmenu_release(impl->appmenu);
			// org_kde_kwin_appmenu_manager has no destroy request in the protocol (it's a
			// long-lived global, same convention as other Wayland "manager" singletons) - left
			// bound for the process lifetime.
			delete impl;
			m_impl = nullptr;
		}
	}
}
