#!/bin/bash

printf "\n============================================[ Building Library ]============================================\n\n"
\cp -r ../extra/* ./
if [ "$(expr substr $(uname -s) 1 5)" == "Linux" ]; then
    make
elif [ "$(expr substr $(uname -s) 1 10)" == "MINGW64_NT" ]; then
    mingw32-make.exe
fi

if [ $? -eq 0 ]; then
    printf "\n==============================================[ Running Test ]==============================================\n\n"
    ./ostd_test
    printf "\n============================================================================================================\n\n"
fi